# frozen_string_literal: true

require_relative 'boot'
require 'sequel/core'
Sequel.extension :migration

namespace :db do
  desc 'Run database migrations'
  task :migrate do
    Sequel::Migrator.run(Sidereal.dependencies['db'], 'db/migrations')
    puts 'Migrations complete.'
  end

  desc 'Generate the Sourced migration file into db/migrations'
  task :sourced_migration do
    Sidereal.dependencies['sourced'] # Sourced, set up on the app's database
    Sourced.store.copy_migration_to do
      "db/migrations/#{Time.now.strftime('%Y%m%d%H%M%S')}_create_sourced_tables.rb"
    end
    puts 'Sourced migration file created in db/migrations/'
  end

  desc 'Wipe all events from the Sourced store'
  task :reset do
    Sidereal.dependencies['sourced']
    Sourced.store.clear!
    puts 'All events deleted.'
  end
end
