# frozen_string_literal: true

source "https://rubygems.org"

gem "sidereal", path: "../.."
gem "falcon"

# Sourced backend for the Sidereal integration (store + dispatcher).
gem 'sourced', github: 'ismasan/sourced', branch: 'ccc'

gem "ruby_llm", "~> 1.14"
gem 'irb'

gem "dotenv", "~> 3.2"
gem "kramdown"
